config/routes.rb
Rails.application.routes.draw do

  resources :players

  resources :clubs

  resources:tournaments

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
  has_many :players
  has_many :tournaments
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :club, optional:true
  has_and_belongs_to_many :tournaments
end

app/models/tournament.rb
class Tournament < ApplicationRecord
   has_and_belongs_to_many :players
   belongs_to :club, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController

  #Create
  def new
    @club = Club.new
  end

  def create
    Club.create club_params

    redirect_to clubs_path

  end

  #Read
  def index
   @clubs = Club.all
  end

  def show
   @club = Club.find params[:id]
   @club_players = @club.players
   @upcoming_comps = @club.tournaments.where state: 'true'
   @past_comps = @club.tournaments.where state: 'false'
  end

  #Update
  def edit
    @club = Club.find params[:id]
  end

  def update
    club = Club.find params[:id]
    club.update club_params

    redirect_to club_path(club.id)
  end

  #Destroy
  def destroy
    Club.destroy params[:id]
    redirect_to clubs_path
  end
end


private

def club_params

  params.require(:club).permit(:logo, :name, :address, :opening, :courts, :courttype, :pro, :manager, :amenities, :coaches, :image)

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  # Create
  def new
      @player = Player.new
  end

  def create
    Player.create player_params

    redirect_to players_path
  end

  # Read
  def index
    @male = Player.where gender: 'Male'
    @female = Player.where gender: 'Female'
    @female_sort = @female.sort_by { |p| p[:ausranking] }
    @male_sort = @male.sort_by { |p| p[:ausranking] }
  end

  def show
    @player = Player.find params[:id]
    @player_club = @player.club.name
    @club = @player.club
    @upcoming_tournaments = @player.tournaments.where state: 'true'
    @past_tournaments = @player.tournaments.where state: 'false'
  end

  # Update
  def edit
    @player = Player.find params[:id]
  end

  def update
    player = Player.find params[:id]
    player.update player_params

    redirect_to player_path(player.id)
  end

 #Destroy
  def destroy
    Player.destroy params[:id]
    redirect_to players_path
  end
end

private

def player_params

  params.require(:player).permit(:name, :dob, :gender, :nationality, :suburb, :city, :playinghand, :nswrating, :ausranking, :win, :racquet, :coach, :image)


end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController

  def new
    @tournament = Tournament.new
  end

  def create
    Tournament.create tournament_params
    redirect_to tournaments_path
  end

  def index
    @upcomingtournaments = Tournament.where state: true
    @pasttournaments = Tournament.where state: false
  end

  def show
    @tournament = Tournament.find params[:id]

    @mens_winner = Player.find @tournament.menswinner

    @female_winner =  Player.find @tournament.femalewinner

    @mens_runner = Player.find @tournament.mensrunnerup

    @female_runner = Player.find @tournament.femalerunnerup

    @mens_semi = Player.find @tournament.menssemifinalist

    @female_semi = Player.find @tournament.femalesemifinalist

    @mens_quarters = Player.find @tournament.mensquarterfinalist

    @female_quarters = Player.find @tournament.femalequarterfinalist

  end

  def edit

  end

  def update
  end

  def destroy
  end
end

  private

  def tournament_params

  params.require(:tournament).permit(:imageclub, :name, :date, :time)

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/clubs/_club.html.erb
<%= form_for @club do |f| %>

  <%= f.label :logo, 'Upload club Logo URL' %>
  <%= f.text_field :name %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :opening, 'Opening Hours' %>
  <%= f.text_field :opening %>

  <%= f.label :courts, 'Number of Courts' %>
  <%= f.text_field :courts %>

  <%= f.label :courttype, 'Court Surface' %>
  <%= f.text_field :courttype %>

  <%= f.label :pro, 'Professional' %>
  <%= f.text_field :pro %>

  <%= f.label :manager %>
  <%= f.text_field :manager %>

  <%= f.label :amenities, 'Club Info' %>
  <%= f.text_area :amenities %>

  <%= f.label :coaches, 'Coaching Staff' %>
  <%= f.text_field :coaches %>

  <%= f.label :image, 'Upload club image URL' %>
  <%= f.text_field :image %>

  <%= f.submit :submit %>

   <br>
<% end %>

app/views/clubs/edit.html.erb
<h2>Edit<%= @club.name %></h2>

<%= render partial: 'club' %>

app/views/clubs/index.html.erb
<h2>NSW Clubs</h2>

<ul>
  <% @clubs.each do |club| %>
  <div>
      <li><img class ="logo" src="<%= club.logo %>" alt="Club logo"><%= link_to club.name, club_path(club.id) %></li>
  </div>
  <% end %>
</ul>

app/views/clubs/new.html.erb
<h2>Add New Club</h2>

<%= render partial: 'club' %>

app/views/clubs/show.html.erb
<% if @club.logo.present? %>
<%= image_tag @club.logo, alt: @club.name, class: 'clublogo' %>
<% end %>

<% if @club.image.present? %>
<%= image_tag @club.image, alt: @club.name, class: 'clublogo' %>
<% end %>

<h2>
  <%= @club.name %>
</h2>

<%= link_to 'Delete club', club_path(@club.id), method: 'delete' %>
|
<%= link_to 'Edit Club', edit_club_path(@club.id) %>

<div class="club">
  <p><strong>Address:</strong> <%= @club.address %></p>
  <p><strong>Opening Hours:</strong> <%= @club.opening %></p>
  <p><strong>Number Of Courts:</strong> <%= @club.courts %></p>
  <p><strong>Court Type:</strong> <%= @club.courttype %></p>
  <p><strong>Professional:</strong> <%= @club.pro %></p>
  <p><strong>Manager:</strong> <%= @club.manager %></p>
  <p><strong>Coach/Coaches:</strong> <%= @club.coaches %></p>
</div>

<aside class="">
  <p><strong>Club Info:</strong> <%= @club.amenities%></p>
</aside>

<ul>
  <li>Members:</li>
  <% @club_players.each do |player| %>
  <li class ="underline">
  <%= link_to player.name, player_path(player.id) %>
  </li>

  <% end %>
</ul>

<ul>
  <li>Upcoming Tournaments at The Club:</li>
  <br>
  <% @upcoming_comps.each do |tournament| %>
  <li class ="underline">
  <%= link_to tournament.name, tournament_path(tournament.id) %> <%= tournament.date %>
  </li>

  <% end %>
</ul>

<hr>

<ul>
  <li>Past Tournaments at The Club:</li>
  <br>
  <% @past_comps.each do |tournament| %>
  <li class ="underline">
  <%= link_to tournament.name, tournament_path(tournament.id) %> <%= tournament.date %>
  </li>

  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tennis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Istok+Web|Open+Sans&display=swap" rel="stylesheet">
  </head>

  <body>
    <header>

    <h1>NSW Tennis App</h1>

    <%= link_to 'Player Index', players_path %>
    |
    <%= link_to 'Register a Player', new_player_path %>
    |
    <%= link_to 'NSW Clubs', clubs_path %>
    |
    <%= link_to 'Register a Club', new_club_path  %>
    |
    <%= link_to "Tournaments Index", tournaments_path %>
    |
    <%= link_to 'Register a Tournament', new_tournament_path  %>

    </header>


    <%= yield %>

    <footer>

    &copy Tennis NSW, 2020

    </footer>

  </body>
</html>

app/views/players/_form.html.erb
<%= form_for @player do |f| %>

<%= f.label :name, 'Name:' %>
<%= f.text_field :name %>

<%= f.label :dob, 'Date of Birth:' %>
<%= f.text_field :dob%>

<%= f.label :gender, 'Gender:' %>
<%= f.text_field :gender %>

<%= f.label :nationality, 'Nationality:' %>
<%= f.text_field :nationality %>

<%= f.label :suburb, 'Suburb:' %>
<%= f.text_field :suburb %>

<%= f.label :city, 'City:' %>
<%= f.text_field :city %>

<%= f.label :playinghand, 'Playing Hand:' %>
<%= f.text_field :playinghand %>

<%= f.label :nswrating, 'NSW Rating:' %>
<%= f.text_field :nswrating %>

<%= f.label :ausranking, 'Australian Ranking:' %>
<%= f.text_field :ausranking %>

<%= f.label :win, 'Win %:' %>
<%= f.text_field :win %>

<%= f.label :racquet, 'Racquet:' %>
<%= f.text_field :racquet %>

<%= f.label :coach, 'Coach:' %>
<%= f.text_field :coach%>

<%= f.label :image, 'Image URL:' %>
<%= f.text_field :image %>

<%= f.submit :submit %>

<% end %>

app/views/players/edit.html.erb
<h1>Edit</h1>

<%= render partial: 'form' %>

app/views/players/index.html.erb
<h2>NSW Tennis Players</h2>

<h3> Male Players: </h3>

<table>
<tr>
  <th>
    Ranking:
  </th>
  <th>
    Name
  </th>
  <th>
    Nationality
  </th>
</tr>

<% @male_sort.each do |player| %>
<tr>
  <td>
    <ul>
    <li><%= player.ausranking %>
    </ul>
  </td>
  <td>
    <ul>
    <li><%= link_to player.name, player_path(player.id) %>
    </ul>
  </td>
  <td>
    <ul>
    <li><%= player.nationality %>
    </ul>
  </td>
    <% end %>
</tr>
</table>

<hr>

<h3> Female Players: </h3>

<table>
<tr>
  <th>
    Ranking
  </th>
  <th>
    Name
  </th>
  <th>
    Nationality
  </th>
</tr>
<% @female_sort.each do |player| %>
<tr>
  <td>
    <ul>
    <li><%= player.ausranking %>
    </ul>
  </td>
  <td>
    <ul>
    <li><%= link_to player.name, player_path(player.id) %>
    </ul>
  </td>
  <td>
    <ul>
    <li><%= player.nationality %>
    </ul>
  </td>
    <% end %>
</tr>
</table>

app/views/players/new.html.erb
<h1>Add New Player</h1>

<%= render partial: 'form' %>

app/views/players/show.html.erb
<h2><%= @player.name %></h2>

<%= link_to 'Edit Player', edit_player_path(@player.id) %>
|
<%= link_to 'Delete Player', player_path(@player.id), method: 'delete' %>

<br><br>

<% if @player.image.present? %>

<%= image_tag @player.image, alt: @player.name, class: 'player' %>

<% end %>

<p><strong>Club: </strong><%=link_to @player_club, club_path(@club.id)%></p>
<p><strong>Date of Birth: </strong><%=@player.dob%></p>
<p><strong>Nationality: </strong><%=@player.nationality%></p>
<p><strong>Suburb: </strong><%=@player.suburb %></p>
<p><strong>City: </strong><%=@player.city %></p>
<p><strong>Playing Hand: </strong><%=@player.playinghand%></p>
<p><strong>NSW Rating: </strong><%=@player.nswrating%></p>
<p><strong>Aus Ranking: </strong><%=@player.ausranking%></p>
<p><strong>Win %:</strong> <%=@player.win %></p>
<p><strong>Racquet:</strong> <%=@player.racquet %></p>
<p><strong>Coach:</strong> <%=@player.coach %></p>

<ul>
  <li>Upcoming Tournaments:</li>
  <br>
  <% @upcoming_tournaments.each do |tournament| %>
  <li class ="underline">
  <%= link_to tournament.name, tournament_path(tournament.id) %> <%= tournament.date %>
  </li>

  <% end %>
</ul>

<hr>

<ul>
  <li>Past Tournaments:</li>
  <br>
  <% @past_tournaments.each do |tournament| %>
  <li class ="underline">
  <%= link_to tournament.name, tournament_path(tournament.id) %> <%= tournament.date %>
  </li>

  <% end %>
</ul>

app/views/tournaments/edit.html.erb
<h1>Tournaments#edit</h1>
<p>Find me in app/views/tournaments/edit.html.erb</p>

app/views/tournaments/index.html.erb
<h2>Upcoming Tournaments</h2>

<ul>
  <% @upcomingtournaments.each do |tournament| %>
  <li>
    <strong>Name: </strong><%= link_to tournament.name, tournament_path(tournament.id) %> <strong>Date:</strong> <%= tournament.date %>
  </li>
  <% end %>
</ul>

<h2> Past Tournaments</h2>

<ul>
  <% @pasttournaments.each do |tournament| %>
  <li>
<strong>Name: </strong><%= link_to tournament.name, tournament_path(tournament.id) %><strong>Date: <%= tournament.date %></strong>
  </li>
  <% end %>
</ul>

app/views/tournaments/new.html.erb
<h1>Register a Tournament</h1>

<h2>Please fill out these sections :</h2>

<%= form_for @tournament do |f| %>

  <%= f.label :imageclub, '1. Enter Logo URL of the Tournament:' %>
  <%= f.text_field :imageclub %>

  <%= f.label :name, '2. Enter the Tournament Name:' %>
  <%= f.text_field :name %>

  <%= f.label :date, '3. Enter the Tournament Date:' %>
  <%= f.text_field :date %>

  <%= f.label :time, '4. Enter the time of the tournament' %>
  <%= f.text_field :time %>

  <%= f.submit :submit %>

   <br>
<% end %>
<!-- </form> -->

app/views/tournaments/show.html.erb
<h2>
  <%= @tournament.name %>
</h2>

<% if @tournament.imageclub.present? %>

<%= image_tag @tournament.imageclub, alt: @tournament.name, class: 'player' %>
<% end %>


<p><strong>Date:</strong> <%= @tournament.date %></p>
<p><strong>Time:</strong> <%= @tournament.time %></p>

<h2><strong>Mens Winner: </strong><%= @mens_winner.name%> (<%= @mens_winner.club.name %> Tennis Club)</h2>

<%= image_tag @tournament.winnermaleimage , alt: @mens_winner.name, class: 'player' %>

<p><strong>Mens Runner Up: </strong> <%= @mens_runner.name %> (<%= @mens_runner.club.name %> Tennis Club)</p>

<p><strong>Mens Semi Finalist: </strong> <%= @mens_semi.name  %> (<%= @mens_semi.club.name %> Tennis Club) </p>

<p><strong>Mens Quarter Finalist: </strong> <%= @mens_quarters.name %> (<%= @mens_quarters.club.name %> Tennis Club)</p>



<h2><strong>Female Winner: </strong><%=   @female_winner.name %> (<%= @female_winner.club.name %> Tennis Club)</h2>

<%= image_tag @tournament.winnerfemaleimage, alt: @female_winner.name, class: 'player' %>

<p><strong>Female Runner Up: </strong> <%= @female_runner.name  %> (<%= @female_runner.club.name %> Tennis Club)</p>

<p><strong>Female Semi Finalist: </strong> <%= @female_semi.name %> (<%= @female_semi.club.name %> Tennis Club)</p>

<p><strong>Female Quarter Finalist: </strong> <%= @female_quarters.name %> (<%= @female_quarters.club.name %> Tennis Club)</p>